#!/bin/bash
# Generate Dockerfile with layered binary cache

set -euo pipefail

CACHE_DIR="${1:-cache-out}"
OUTPUT="${2:-docker/Dockerfile.cached}"

if [[ ! -f "$CACHE_DIR/layers.txt" ]]; then
  echo "Error: $CACHE_DIR/layers.txt not found"
  exit 1
fi

LAYERS=$(cat "$CACHE_DIR/layers.txt")
NUM_LAYERS=$(echo "$LAYERS" | wc -l)

echo "Generating $OUTPUT with $NUM_LAYERS cache layers"

cat > "$OUTPUT" << 'HEADER'
# Auto-generated Dockerfile with layered binary cache
# Do not edit manually - regenerated by scripts/generate_dockerfile.sh

ARG BASE_IMAGE=ghcr.io/hypertidy/gdal-r-full:latest
FROM ${BASE_IMAGE}

ENV R_LIBS_SITE=/usr/local/lib/R/site-library
HEADER

# Add each layer as a separate COPY (creates separate Docker layers)
i=1
for layer in $LAYERS; do
  pkg_count=$(ls -1 "$CACHE_DIR/$layer" 2>/dev/null | wc -l || echo 0)
  echo "" >> "$OUTPUT"
  echo "# Layer $i: $pkg_count packages" >> "$OUTPUT"
  echo "COPY cache-out/$layer/ \${R_LIBS_SITE}/" >> "$OUTPUT"
  ((i++))
done

cat >> "$OUTPUT" << 'FOOTER'

# Copy check script
COPY scripts/check_one.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/check_one.sh

# Verify key packages load
RUN Rscript -e "\
  for (pkg in c('sf', 'terra')) { \
    if (requireNamespace(pkg, quietly = TRUE)) { \
      cat(sprintf('%s: OK\n', pkg)) \
    } else { \
      cat(sprintf('%s: NOT FOUND\n', pkg)) \
    } \
  }"

# Copy test manifest
COPY cache-out/test_manifest.csv /opt/test_manifest.csv
COPY cache-out/build_summary.json /opt/build_summary.json
FOOTER

echo "Generated $OUTPUT"
cat "$CACHE_DIR/layer_manifest.csv"
