#!/bin/bash
# generate_dockerfile.sh - Generate Dockerfile.cached from built layers
# Usage: ./generate_dockerfile.sh <cache_dir> <output_dockerfile>

set -euo pipefail

CACHE_DIR="${1:-cache-out}"
OUTPUT="${2:-docker/Dockerfile.cached}"

# Check required files exist
if [ ! -f "$CACHE_DIR/layer_manifest.csv" ]; then
  echo "ERROR: $CACHE_DIR/layer_manifest.csv not found"
  exit 1
fi

# Count layers
NUM_LAYERS=$(tail -n +2 "$CACHE_DIR/layer_manifest.csv" | wc -l)

echo "Generating $OUTPUT with $NUM_LAYERS cache layers"

cat > "$OUTPUT" << 'HEADER'
# Auto-generated Dockerfile with layered binary cache
# Do not edit manually - regenerated by scripts/generate_dockerfile.sh

ARG BASE_IMAGE=ghcr.io/hypertidy/gdal-r-full:latest
FROM ${BASE_IMAGE}

ENV R_LIBS_SITE=/usr/local/lib/R/site-library
HEADER

# Add layer COPY commands
for i in $(seq -f "%02g" 1 $NUM_LAYERS); do
  LAYER_DIR="$CACHE_DIR/layer$i"
  if [ -d "$LAYER_DIR" ]; then
    PKG_COUNT=$(ls -1 "$LAYER_DIR" | wc -l)
    echo "" >> "$OUTPUT"
    echo "# Layer $i: $PKG_COUNT packages" >> "$OUTPUT"
    echo "COPY $CACHE_DIR/layer$i/ \${R_LIBS_SITE}/" >> "$OUTPUT"
  fi
done

cat >> "$OUTPUT" << 'FOOTER'

# Install CLI tools
COPY scripts/check_one.sh /usr/local/bin/
COPY scripts/gdalcheck-status /usr/local/bin/
COPY scripts/gdalcheck-pkg /usr/local/bin/
COPY scripts/R/summary_cache_build.R /usr/local/bin/
RUN chmod +x /usr/local/bin/check_one.sh \
             /usr/local/bin/gdalcheck-status \
             /usr/local/bin/gdalcheck-pkg

# Verify key packages load
RUN Rscript -e "\
  for (pkg in c('sf', 'terra', 'gdalraster', 'vapour')) { \
    if (requireNamespace(pkg, quietly = TRUE)) { \
      cat(sprintf('%s: OK\n', pkg)) \
    } else { \
      cat(sprintf('%s: NOT FOUND\n', pkg)) \
    } \
  }"

# Copy manifests
COPY cache-out/test_manifest.csv /opt/test_manifest.csv
COPY cache-out/build_summary.json /opt/build_summary.json

# Default entrypoint
CMD ["R"]
FOOTER

echo "Generated $OUTPUT"
cat "$CACHE_DIR/layer_manifest.csv"
